config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "application#home"

  resources :organizations do
    resources :users do
      get "join"
      get "leave"
    end
  end

  resources :users do
    resources :shifts
  end
end

app/views/partials/_add_organization_form.html.erb
<%= form_with model: @organization, url: organizations_path, method: "post" do |f| %>

    <%= f.text_field :name, placeholder: "name", autofocus: true %><br><br>
    <%= f.text_field :hourly_rate, placeholder: "hourly rate", autofocus: true %><br><br>

    <%= f.submit "add", :class => "button" %>
<% end %>

app/views/partials/_add_shift_form.html.erb
<%= form_with model: @shift, url: user_shifts_path(current_user, @shift), method: "post" do |f| %>

    <%= f.hidden_field :organization_id, value: current_user.organization.id  %>

    <div class="field-labels">
        <%= f.label :start, "shift start:" %>
        <%= f.datetime_select :start, autofocus: true %><br><br>
        
        <%= f.label :finish, "shift end:" %>
        <%= f.datetime_select :finish, autofocus: true %><br><br>
        
        <%= f.label :break_length, "break length:" %>
        <%= f.text_field :break_length, placeholder: "(in minutes)", autofocus: true %>
    </div><br>

    <%= f.submit "add", :class => "button" %>
<% end %>

app/views/partials/_edit_organization_form.html.erb
<%= form_with model: @organization, url: organization_path(@organization), method: "patch" do |f| %>
    <%= f.text_field :name, placeholder: "name", autofocus: true %><br><br>
    <%= f.text_field :hourly_rate, placeholder: "hourly rate", autofocus: true %><br><br>

    <%= f.submit "edit", :class => "button" %>
<% end %>

app/views/partials/_edit_shift_form.html.erb
<%= form_with model: @shift, url: user_shift_path(current_user, @shift), method: "patch" do |f| %>
               
    <%= f.hidden_field :organization_id, value: current_user.organization.id  %>

    <div class="field-labels">
        <%= f.label :start, "shift start:" %>
        <%= f.datetime_select :start, autofocus: true %><br><br>
        
        <%= f.label :finish, "shift end:" %>
        <%= f.datetime_select :finish, autofocus: true %><br><br>
        
        <%= f.label :break_length, "break length:" %>
        <%= f.text_field :break_length, placeholder: "(in minutes)", autofocus: true %>
    </div><br>

    <%= f.submit "edit", :class => "button" %>

<% end %>

app/views/partials/_links.html.erb
<center>
        <ul>
            <li id="sign-up"><%= link_to "sign up", new_user_registration_path, :class => "button" %></li>
            <li id="log-in"><%= link_to "log in", new_user_session_path, :class => "button" %></li>
        </ul>
</center>

app/views/partials/_name.html.erb
<h2 class="gradient-text"><%= current_user.name %></h2><br>
<div class="smaller-margins">
    <%= button_to "sign out", destroy_user_session_path, method: "delete", :class => "button"%>
</div>

app/views/partials/_organizations_list.html.erb
<div class="organizations-container">
    <% @organizations = Organization.all %>
        <% @organizations.map do |organization| %>
            <div class="organizations">
                <%= link_to(organization.name, organization_path(organization)) %>
            </div>
        <% end %>
</div>

app/views/partials/_shift_errors.html.erb
<% if @shift.errors.any? %>
    <% @shift.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>