config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "application#home"

  resources :organizations do
    resources :users do
      get "join"
      get "leave"
    end
  end

  resources :users do
    resources :shifts
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organization, optional: true
  has_many :shifts, dependent: :destroy
  
#   join table?
	has_many :organizations_with_shifts, through: :shifts, source: :organization

  validates_uniqueness_of :email
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :organization_id, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :organization_id, :password_confirmation])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action: :find_user, only: [:show, :edit, :update, :destroy]
    # before_action: :find_organization, only: [:create, :new]
    # before_action: :currently_logged_in, only: [:edit, :update, :destroy]
    
        def index
            @organization = Organization.includes(:users).find(params[:organization_id])
            @users = User.all
        end
    
        def create
            @user = User.new(user)
    
            if @user.save
                flash.notice = "welcome!"
                session[:user_id] = @user.id
    
                redirect_to root_path
            else 
                @user.errors.full_messages

                render :new 
            end
        end
    
        def new
            @user = User.new
        end
    
        def edit
        end
    
        def show
            @organization = current_user.organization
        end
    
        def update
            if @user.update(user_params)
    
                redirect_to @user
            else
                render :edit
            end
        end

        def join
            @organization = Organization.find(params[:organization_id])
            current_user.update_attribute(:organization_id, @organization.id)

            redirect_to root_path
        end

         def leave
            current_user.update_attribute(:organization_id, nil)

            redirect_to root_path
        end
    
        def destroy
            @user.destroy
            
            redirect_to login_path
        end
    
    private
        def find_user
            @user = User.find_by(params[:id])
        end

        # def find_organization
        #     @organization = Organization.find(params[:id])
        # end
    
        def currently_logged_in
            unless logged_in?
                flash.alert = "oops, please log in"
    
                redirect_to login_path
            end
        end
    
        def user_params
            params.require(:user).permit(:organization_id, :name, :email, :password)
        end
end 

app/views/users/show.html.erb
<h1>ADNAT</h1> 

<% if current_user %>
    <div class="user-profile-container">
        <center>
            <%= render "partials/name" %>

            <div class="navigation">
                <div class="flex-row">
                    <%= link_to "← back", root_path %>
                </div>
            </div>
        </center>

        <div class="user-profile-content">
            <% if current_user.organization_id.nil? %>
                    <center>
                        <br><br><br><h3 class="gradient-text">hello!</h3>
                        <h4>select "home" to join or add an organization</h4>
                    </center>
            <% else %>
                    <div class="flex-row">
                        <h3>your organization:</h3> 
                        <h3 style="color: #D4AC0D; margin-left: .4rem"><%= @organization.name %></h3>
                    </div>

                    <div class="smaller-margins"> 
                        <%= link_to 'leave', organization_user_leave_path(current_user, @organization), :class => "button" %>
                        <%= link_to "add shift", new_user_shift_path(current_user), :class => "button" %>
                    </div>

                <h5>hourly rate: </h5>
                <p>$<%= @organization.hourly_rate %></p>

                <h5>employees:  </h5>
                <% users = @organization.users %>
                <% users.each do |user| %>
                    <p><%= user.name %></p>
                <% end %>

                <h5>shifts:</h5>
                <% shifts = @organization.shifts %>
                <% shifts.each do |shift| %>
                    <div class="bottom-border">
                        <div class="flex-row">
                            <p style="font-size:.8rem;">employee:<br> <%= shift.user_name %></p>
                            <p style="font-size:.8rem;">shift date:<br> <%= shift.start.strftime("%m-%d-%Y") %></p>
                            <p style="font-size:.8rem;">start time:<br> <%= shift.start.strftime("%I:%M%p") %></p>
                            <p style="font-size:.8rem;">end time:<br> <%= shift.finish.strftime("%I:%M%p") %></p>
                            <p style="font-size:.8rem;">break length:<br> <%= shift.break_length %> mins<p>
                            <p style="font-size:.8rem;">hours worked:<br>
                                <% @shift_length = shift.finish.to_time - shift.start.to_time %>
                                <% @length_in_minutes = @shift_length / 60 %>
                                <% @minutes_worked = @length_in_minutes - shift.break_length %>
                                <% @hours_worked = @minutes_worked / 60 %>

                                <%= @hours_worked %>
                            </p>
                            <p style="font-size:.8rem;">wages earned: 
                                <% @shift_cost = @hours_worked * shift.organization_hourly_rate %>

                                $<%= @shift_cost %>
                            </p>

                            <% if shift.user_id == current_user.id %>
                                <div class="increase-margin-right"
                                    <br><%= link_to "edit", edit_user_shift_path(current_user, shift), :class => "button" %>
                                </div>
                                <%= button_to "delete", user_shift_path(current_user, shift), method: "delete", :class => "button" %>
                            <% else %>
                                <p></p>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
<% else %>
    <%= render "partials/links" %>
<% end %>