config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "application#home"

  resources :organizations do
    resources :users do
      get "join"
      get "leave"
    end
  end

  resources :users do
    resources :shifts
  end
end

app/models/organization.rb
class Organization < ApplicationRecord

    has_many :users
    
    # join table?
    has_many :shifts, dependent: :destroy
    has_many :users_with_shifts, through: :shifts, source: :user 

    validates_presence_of :name
end

app/controllers/organization_controller.rb
class OrganizationsController < ApplicationController
    before_action :find_organizations, only: [:show, :edit, :update, :destroy, :join, :leave]

    def index
        @organizations = current_user.organizations
    end

    def new
       @organization = Organization.new
    end
    
    def create
        @organization = current_user.organizations.build(organization_params)
        @organization.user_id = current_user.id
        
        if @organization.save
            flash.notice = "organization created"

            redirect_to user_organization_path(current_user, @organization)
        else
            @organization.errors.full_messages

            render :new
            # redirect_to root_path
        end
    end

    def show
    end

    def edit
    end

    def update
        if @organization.update(organization_params)

            redirect_to user_organization_path(current_user, @organization)
        else
            @organization.errors.full_messages
            
            render :edit
        end
    end

    def destroy
        @organization.destroy
    
        redirect_to user_organizations_path(current_user)
    end

    def join
        current_user.update_attribute(:organization_id, @organization.id)

        redirect_to @organization
        # redirect_to user_organizations_path(current_user)
    end

    def leave
        current_user.update_attribute(:organization_id, nil)

        redirect_to user_organizations_path(current_user)
    end

    private 
        def find_organizations
            @organization = Organization.find(params[:id])
        end

        def organization_params
            params.require(:organization).permit(:name, :hourly_rate)
        end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
    before_action :find_organizations, only: [:show, :edit, :update, :destroy]

    def index
        @organizations = Organization.all
    end

    def new
       @organization = Organization.new
    end
    
    def create
        @organization = Organization.new(organization_params)

        if @organization.save 
            flash.notice = "organization saved"

            # redirect_to root_path
            redirect_to organization_path(@organization)
        else
            @organization.errors.full_messages

            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @organization.update(organization_params)

            redirect_to organization_path(@organization)
        else
            @organization.errors.full_messages
            
            render :edit
        end
    end

    def destroy
        @organization.destroy
    
        redirect_to root_path
    end

    private 
        def find_organizations
            @organization = Organization.find(params[:id])
        end

        def organization_params
            params.require(:organization).permit(:name, :hourly_rate)
        end
end

app/views/organizations/new.html.erb
<h1>ADNAT</h1> 

<% if current_user %>
    <div class="profile-container">
        <center>
            <%= render "partials/name" %>

            <div class="navigation">
                <div class="flex-row">
                    <%= link_to "← back", :back %>
                </div>
            </div>
        </center>
            
            <div class="profile-content">
                <h3>add a new organization</h3>
                <%= render "partials/add_organization_form" %>
               
                <h3>existing organizations:</h3>
                <%= render "partials/organizations_list" %>
            </div>
    </div>
<% else %>
    <%= render "partials/links" %>
<% end %>

app/views/organizations/show.html.erb
<h1>ADNAT</h1> 

<% if current_user %>
    <div class="profile-container">
        <center>
            <%= render "partials/name" %>

            <div class="navigation">
                <div class="flex-row">
                    <%= link_to "← back", root_path %>
                </div>
            </div>
        </center>

        <div class="profile-content">
                <h3 style="color: #D4AC0D; text-align:center;"><%= @organization.name %></h3>

                <% if current_user.organization_id.nil? %>
                    <div class="smaller-margins">
                        <div class="float-left">
                            <%= link_to 'join', organization_user_join_path(@organization, current_user), :class => "button" %> 
                        </div>
                    </div>
                <% else %>
                    <p></p>
                <% end %>

            <br><br><h5>hourly rate: </h5>
            <p>$<%= @organization.hourly_rate %></p>
            
            <h5>members: </h5>
            <% users = @organization.users %>
            <% users.each do |user| %>
                <p><%= user.name %></p>
            <% end %>
    
            <% if current_user.organization_id == @organization.id %>
                <h3>edit current organization</h3>
                <%= render "partials/edit_organization_form" %><br>
                
                <% else %>
                    <h3>delete current organization</h3>
                    <%= button_to "delete", @organization, method: "delete", :class => "button" %>
            <% end %>
        </div>
    </div>
<% else %>
    <%= render "partials/links" %>
<% end %>