config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "application#home"

  resources :organizations do
    resources :users do
      get "join"
      get "leave"
    end
  end

  resources :users do
    resources :shifts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    # adds name field to devise
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :order_by_recently_created

    def all_shifts
     @shifts = Shift.all
    end

    def order_by_recently_created
     @ordered_shifts = all_shifts.by_recently_created
    end

    protected
         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :organization_id, :email, :password, :password_confirmation)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :organization_id, :email, :password, :current_password)}
         end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<h1>ADNAT</h1> 

<% if current_user %>  
    <div class="profile-container">
        <center>
            <%= render "partials/name" %>

            <div class="navigation">
                <div class="flex-row">
                    <%= link_to "add organization", new_organization_path %>

                    <% if current_user.organization_id.nil? %>
                        <p></p>
                    <% else %>
                        <%= link_to "add shift", new_user_shift_path(current_user) %>
                    <% end %>
                </div>
            </div>
    
            <div class="profile-content">
                <h3>your organization:</h3>
                <% if current_user.organization_id.nil? %>
                    <p>please join an organization by selecting below</p>
                <% else %>
                    <p><%= link_to(current_user.organization.name, user_path(current_user)) %></p>
                <% end %>

                <h3>all organizations:</h3>
                <%= render "partials/organizations_list" %>
            </div>
        </center>
    </div>
<% else %>
   <%= render "partials/links" %>
<% end %>